/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Service, Project } from './types';
import imgCommercial from './assets/images/regenerated_image_1779550936996.png';
import imgOffice from './assets/images/regenerated_image_1779550938782.png';
import imgBooth from './assets/images/regenerated_image_1779550940143.png';

export const ServicesData: Service[] = [
  {
    id: 'commercial',
    titleAr: 'تنفيذ المحلات التجارية',
    titleEn: 'Retail Store Fit-out',
    descriptionAr: 'نصنع لعلامتك التجارية حضوراً حسّياً مبهراً يلفت الأنظار، عبر تنفيذ وتشطيب معارض التجزئة ومحلات العطور والملابس الفاخرة بأعلى معايير الإتقان والدقة الهندسية.',
    descriptionEn: 'We craft an elegant physical presence for your brand, constructing and finishing luxury showrooms, fragrance boutiques, and high-end fashion stores with architectural precision.',
    icon: 'Store',
    image: imgCommercial,
    specsAr: ['تشطيب كامل للأقسام الكبرى', 'تصنيع وتوريد وحدات العرض الخشبية والمعدنية المخصصة', 'أنظمة الإضاءة الدراماتيكية لإبراز المنتجات', 'دمج الهويات البصرية للعلامات العالمية والمحلية'],
    specsEn: ['Turnkey luxury retail checkout and shopping halls', 'Custom woodwork and metal display units manufacturing', 'Dramatic aesthetic lighting plans for product highlights', 'Seamless brand identity integration for global & local brands']
  },
  {
    id: 'office',
    titleAr: 'تنفيذ المكاتب والشركات',
    titleEn: 'Office & Corporate Fit-out',
    descriptionAr: 'نصمم وننفذ بيئات عمل تفاعلية تجمع بين جودة التشطيب والعملية المطلقة، مع مراعاة العزل الصوتي وتوزيع الهياكل، لخلق مساحات تحفز الإنتاجية وتعكس هيبة شركتك.',
    descriptionEn: 'We execute interactive workplaces combining premier finishes with ultimate ergonomics. Featuring sound insulation, acoustic partitions, and structures that boost performance and command prestige.',
    icon: 'Briefcase',
    image: imgOffice,
    specsAr: ['تركيب القواطع الزجاجية والصوتية المبتكرة', 'تنفيذ غرف الاجتماعات الذكية والـ CEO Suites الفاخرة', 'توزيع الإضاءة المريحة للعين وخافضة للجهد', 'تجهيز البنية التحتية المتكاملة للشبكات والتيار الخفيف'],
    specsEn: ['Acoustic double-glazed smart partitions', 'Luxury CEO Suites and premium multimedia boardrooms', 'Anti-glare work-comfort lighting distribution', 'Complete low-voltage utility and networking infrastructure']
  },
  {
    id: 'booth',
    titleAr: 'تنفيذ البوثات والمعارض',
    titleEn: 'Exhibition Booths & Pavilions',
    descriptionAr: 'نحول البوثات المؤقتة إلى معالم معمارية جذابة في المعارض الدولية والفعاليات الكبرى، بإنشاء هياكل هندسية مخصصة وسريعة التجميع تنبض بروح علامتك التجارية.',
    descriptionEn: 'We transform temporary structures into architectural landmarks at international exhibitions and major events, building custom, quick-assembly structures that pulse with your brand identity.',
    icon: 'Layers',
    image: imgBooth,
    specsAr: ['تصنيع الهياكل الخشبية المنحنية والمقساة مسبقاً', 'تركيب شاشات العرض الذكية وحلول التفاعل الرقمي', 'توفير أنظمة إضاءة نيون وميتاليك جذابة', 'سرعة التنفيذ والتفكيك مع الحفاظ على سلامة المواد'],
    specsEn: ['Pre-fabricated custom curved and high-strength timber arches', 'Interactive digital signage and LED walls integration', 'Metallic and vivid neon visual lighting systems', 'High-speed assembly and teardown operations with material retention']
  }
];

export const ProjectsData: Project[] = [
  {
    id: 'rasees_stores',
    titleAr: 'رسيس',
    titleEn: 'Rasees',
    category: 'commercial',
    clientAr: 'رسيس',
    clientEn: 'Rasees',
    year: '2026',
    area: '+800 متر',
    locationAr: '19 مدينة',
    locationEn: '19 Cities',
    descriptionAr: 'تنفيذ وتجهيز سلسلة معارض عطور رسيس الفاخرة الموزعة على ١٩ مدينة بالمملكة، بهوية بصرية راقية وتجهيزات خشبية ومعدنية مخصصة بمصانعنا.',
    descriptionEn: 'Full fit-out and millwork fabrication for the premium Rasees Perfume showrooms network active across 19 cities in Saudi Arabia.',
    mainImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000',
    youtubeId: 'zax71xSms8Q',
    featuresAr: ['تنفيذ تشطيبات فاخرة باللون والمايكروسمنت', 'تصنيع طاولات تجربة العطور والأحزمة ومسارات الإنارة المخصصة', 'توحيد الهوية وإدارة الخدمات اللوجستية لـ 19 مدينة'],
    featuresEn: ['Sleek luxury paint and micro-cement finish application', 'In-house manufacturing of perfume display islands and customized lighting guides', 'Conforming brand standards and nationwide logistics management across 19 cities']
  },
  {
    id: 'akhshab_booth',
    titleAr: 'أخشاب',
    titleEn: 'Akhshab',
    category: 'booth',
    clientAr: 'أخشاب',
    clientEn: 'Akhshab',
    year: '2026',
    area: '250 م',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تصميم وتنفيذ جناح شركة أخشاب بالكامل مستعرضين الفنون الخشبية الراقية والمنحنيات المعمارية الدقيقة مع نظم إنارة مدمجة بالهياكل المؤقتة.',
    descriptionEn: 'A masterfully constructed pavilion for Akhshab Company at Riyadh exhibition, highlighting fluid architectural arches and embedded warm lighting structures.',
    mainImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000',
    youtubeId: 'TA4QZ-Xdx0c',
    featuresAr: ['هياكل خشبية منحنية ذات مواصفات متانة عالية', 'مساحات مدمجة لاستقبال الزوار والتراخيص الذكية', 'إضاءات خطية تبرز الخامات الطبيعية الراقية'],
    featuresEn: ['Precision pre-fabricated high-strength timber curves', 'Optimized client layout and seamless interactive zones', 'Integrated linear task lighting highlighting premium natural wood grains']
  },
  {
    id: 'rasmah_boutique',
    titleAr: 'رسمة',
    titleEn: 'Rasmah',
    category: 'commercial',
    clientAr: 'رسمة',
    clientEn: 'Rasmah',
    year: '2026',
    area: '+500 متر',
    locationAr: 'مواقع متعددة',
    locationEn: 'Multiple Sites',
    descriptionAr: 'تنفيذ وتجهيز سلسلة معارض رسمة بمظهرها الهادئ والمتميز، تعتمد على الحوائط الميكروسمنية المتجانسة ووحدات العروض والتعليق المعدنية المخصصة بمصانعنا.',
    descriptionEn: 'Nationwide commercial boutique rollouts for Rasmah Beauty, constructed with smooth micro-cement walls and custom metal racks.',
    mainImage: 'https://images.unsplash.com/photo-1620052581237-5d36667be337?q=80&w=1000',
    youtubeId: '3yRzjjxxxFI',
    featuresAr: ['أعمال طلاء وجص مايكروسمنت هادئة وراقية', 'تصنيع أرفف وحوامل حديدية صلبة بمقاومة فائقة ومطليات كهربائية', 'دمج أنظمة إضاءة خطية عصرية تبرز المانيكانات والجماليات'],
    featuresEn: ['Artisanal micro-cement and plaster wall layouts', 'Powder-coated customized steel displays with anti-scratch coating', 'Modern linear LED integration focusing on fashion and cosmetics']
  },
  {
    id: 'labkah_boutique',
    titleAr: 'لبكة',
    titleEn: 'Labkah',
    category: 'commercial',
    clientAr: 'لبكة',
    clientEn: 'Labkah',
    year: '2026',
    area: '82',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ ذكي وأنيق لمتجر لبكة بالرياض بمساحة مدمجة تستعرض القطع الفنية والمنتوجات بإطار هندسي مريح وتشطيبات راقية للأخشاب.',
    descriptionEn: 'Intelligent, highly functional compact showroom build for Labkah, utilizing customized joinery and geometric layout design.',
    mainImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000',
    youtubeId: 'llsC6QdaNMY',
    featuresAr: ['جدران ومكعبات خشبية منحنية مصنوعة خصيصاً', 'أضواء تسليط بؤري مبرزة لتجربة غنية', 'أرضيات إيبوكسي عالية المقاومة بمظهر متناسق'],
    featuresEn: ['Handcrafted customized curved timber counters and partition walls', 'Precision product tracking accent spotlights', 'Seamless micro-finish heavy-duty floors with high wear resistance']
  },
  {
    id: 'aromatic_showrooms',
    titleAr: 'أروماتك',
    titleEn: 'Aromatic',
    category: 'commercial',
    clientAr: 'أروماتك',
    clientEn: 'Aromatic',
    year: '2026',
    area: '+800 متر',
    locationAr: '20 مدينة',
    locationEn: '20 Cities',
    descriptionAr: 'تنفيذ وسلسلة فروع أروماتك المتخصصة بالعطور والروائح الراقية بجميع أنحاء المملكة، بتفاصيل جدران عاكسة وأقواس رخامية وإنارة خاشعة.',
    descriptionEn: 'High-end retail fit-out and expansion project for Aromatic perfume lounges, featuring custom mirrors and heavy stone counters.',
    mainImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000',
    youtubeId: 'cbUTtRx0wS4',
    featuresAr: ['مرايا وإطارات مضيئة بدقة وبدون فراغات هوائية', 'طاولات عرض CNC رخامية منفذة خصيصاً', 'أنظمة دمج الفواحات العطرية بذكاء مع فتحات التكييف بالسقف'],
    featuresEn: ['Precision round frame mirrors with flush dynamic halo backlights', 'CNC-cut structural marble display islands from fzyn manufacturing plants', 'Engineered aroma diffusion mechanics merged inside the HVAC output ducts']
  },
  {
    id: 'bluear_booth',
    titleAr: 'بلوار',
    titleEn: 'Bluear',
    category: 'booth',
    clientAr: 'بلوار',
    clientEn: 'Bluear',
    year: '2026',
    area: '600 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'إنشاء وتجهيز الجناح الهندسي الأكبر لشركة بلوار بالرياض بمساحة ٦٠٠ متر مربع، بهياكل فخمة وشاشات تفاعلية ضخمة تحتضن فعاليات العلامة.',
    descriptionEn: 'Construction of the monumental 600sqm exhibition stand for Bluear in Riyadh, blending large-scale wood profiles and integrated LED media walls.',
    mainImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1000',
    youtubeId: 'wJ_GuGB-Sy0',
    featuresAr: ['مسرح عرض ضخم مع هياكل حمل قوية ومخفية', 'تجهيز مناطق VIP فاخرة للاجتماعات المغلقة والجلسات التفاوضية', 'إضاءات غامرة ومحاكاة لمؤثرات بصرية عصرية مذهلة'],
    featuresEn: ['Gigantic main presentation stage with concealed heavy steel supports', 'Double-deck VIP negotiation suites finished with premium carpet', 'Sophisticated dynamic washes and bespoke color accent templates']
  },
  {
    id: 'rasees_booth',
    titleAr: 'رسيس',
    titleEn: 'Rasees (Booth)',
    category: 'booth',
    clientAr: 'رسيس',
    clientEn: 'Rasees',
    year: '2026',
    area: '600 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'إنشاء الجناح المؤقت الضخم لشركة رسيس في معرض الفعاليات لتجربة حسية متفرّدة، بتفاصيل أسقف معلقة وجدران مضيئة وأحدث نظم العرض والتشغيل السريع.',
    descriptionEn: 'The massive 600sqm event pavilion designed and delivered for Rasees Perfumes in Riyadh Front, combining gorgeous ceiling drops and visual retail walls.',
    mainImage: 'https://images.unsplash.com/photo-1620052581237-5d36667be337?q=80&w=1000',
    youtubeId: 'TeocNNVGyK4',
    featuresAr: ['أسقف هيدروليكية مؤقتة فائقة الأمان معلقة بدقة', 'وحدات تجربة واختبار عطور متفاعلة ومضاءة بدقة هندسية', 'سرعة البناء والتفكيك مع تطبيق جودة فوتوغرافية في التشطيب'],
    featuresEn: ['Concealed structural safety cables for ceiling banners', 'Interactive backlit acrylic tester islands from our production lines', 'High speed modular construction maintaining high photographic finish values']
  },
  {
    id: 'floward_office',
    titleAr: 'فلاورد',
    titleEn: 'Floward',
    category: 'office',
    clientAr: 'فلاورد',
    clientEn: 'Floward',
    year: '2026',
    area: '750 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'مكاتب إدارية تفاعلية لشركة فلاورد بالرياض، بمساحات ذات أثاث عصري مريح وغرف إلكترونية ومناطق اجتماعات مبتكرة ومقاهي مدمجة للموظفين.',
    descriptionEn: 'Ultra-modern active corporate headquarters for Floward Riyadh, featuring ergonomic collaborative workspaces and specialized technical media pods.',
    mainImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000',
    youtubeId: 'gIzIJFJQ7Vk',
    featuresAr: ['قواطع زجاجية مزدوجة مبتكرة لعزل الصوت والخصوصية', 'تنفيذ غرف اجتماعات ذكية تفاعلية وشاشات مدمجة', 'تنسيق الإضاءة وتوزيع نباتات السقف الطبيعية والمعالجة'],
    featuresEn: ['Double-glazed floor-to-ceiling office partitions', 'Interactive client meeting rooms and screen-integrated walls', 'Aesthetic indoor biomorphic plants and glare-reduced ceiling lighting layouts']
  },
  {
    id: 'floward_warehouse',
    titleAr: 'مستودع فلاورد',
    titleEn: 'Floward Warehouse',
    category: 'office',
    clientAr: 'مستودع فلاورد',
    clientEn: 'Floward Warehouse',
    year: '2026',
    area: '1000 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'بناء وتشطيب الجزء الإداري والخدمي بمستودع فلاورد العملاق بالرياض، مجهزا لحركات الموظفين والعمليات اللوجستية بمواصفات متانة فائقة وعزل صوتي وحراري ممتاز.',
    descriptionEn: 'The spacious administrative blocks inside the Floward central logistics hub, constructed using heavy-duty materials with active sound barriers.',
    mainImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000',
    youtubeId: '-TiZtJrBLBc',
    featuresAr: ['أرضيات إيبوكسية وحوائط مصفحة ومقاومة للصدمات', 'مكاتب إدارية علوية بإطلالات زجاجية لمراقبة العمليات', 'أنظمة تحكم وطوارئ وتيار خفيف متطورة مدمجة تماماً'],
    featuresEn: ['Industrial epoxy floors and robust impact-resistant wall claddings', 'Mezzanine executive suites with clear tempered viewing screens', 'Fully integrated low-voltage security and centralized operation controls']
  },
  {
    id: 'sscp_office',
    titleAr: 'SSCP Office',
    titleEn: 'SSCP Office',
    category: 'office',
    clientAr: 'SSCP Office',
    clientEn: 'SSCP Office',
    year: '2026',
    area: '100 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ المقر والمكتب التنفيذي لـ SSCP بالرياض، بلمسات معمارية مبتكرة تستغل مساحة الـ ١٠٠ متر بكفاءة متناهية، ومكسوة بأخشاب ورخام فاخر وستيل أسود صلب.',
    descriptionEn: 'Premium luxury executive corporate office executed for SSCP Riyadh, combining space efficiency with handcrafted marble, oak, and steel plates.',
    mainImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1000',
    youtubeId: 'UMGNiZP3Dds',
    featuresAr: ['تشطيب جدران وأسقف فخمة بجانبي الخشب والزجاج والستيل الأسود', 'طاولات ومكتب استقبال رئيسي منحوت من الرخام الصافي والكروم', 'أرضيات باركيه ألماني معزول بالكامل ضد الصوت والمياه'],
    featuresEn: ['Sleek integrated dark steel details with premium wood slats', 'Custom reception desk cut from solid imperial marble with chrome highlights', 'German acoustic water-resistant wooden flooring installations']
  },
  {
    id: 'dorma_booth',
    titleAr: 'دورما',
    titleEn: 'Dorma',
    category: 'booth',
    clientAr: 'دورما',
    clientEn: 'Dorma',
    year: '2026',
    area: '12 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ ذكي لجناح عرض شركة دورما بمساحة مدمجة تبلغ ١٢ متراً مربعاً، مستعرضاً حلول التكنولوجيا والأبواب بمرونة تامة وتشطيبات جذابة.',
    descriptionEn: 'A high-concept smart micro-booth executed for Dorma Riyadh, with ultra-clean mechanics and professional layout utility in just 12sqm.',
    mainImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000',
    youtubeId: 'L1Ss3YQ-BT4',
    featuresAr: ['هيكل معدني وخشي متين وقابل لإعادة التجميع المتكرر', 'لوحات وحوامل تفاعلية متضمنة نماذج الأبواب والتجهيزات', 'تثبيت إضاءة LED غائرة دافئة تركز على التقاطيات الأساسية'],
    featuresEn: ['Sturdy steel-and-timber structure meant for rapid re-assembly', 'Smart interactive product display panels showcasing hardware', 'Warm recessed LED spotlights highlights emphasizing physical interaction']
  },
  {
    id: 'alshaya_stores',
    titleAr: 'الشايع',
    titleEn: 'AlShaya',
    category: 'commercial',
    clientAr: 'الشايع',
    clientEn: 'AlShaya',
    year: '2026',
    area: '+250 متر',
    locationAr: 'مواقع متعددة',
    locationEn: 'Multiple Locations',
    descriptionAr: 'سلسلة تشطيبات وتنفيذ بمواصفات ومعايير عالمية لعلامات تجارية تحت مظلة الشايع بالمملكة، بمزيج غني من الجدران الخشبية الصامتة والأرضيات اللامعة ونظم طلاء معالجة.',
    descriptionEn: 'Masterful commercial store fit-outs and architectural delivery for global boutiques franchised under AlShaya Group across Saudi Arabia.',
    mainImage: 'https://images.unsplash.com/photo-1513885045260-6b15d67e44f9?q=80&w=1000',
    youtubeId: 'KPkM7onavxw',
    featuresAr: ['توريد خشي وتركيب جدران مضادة للرطوبة وتوافق عالي مع البيئة', 'تصنيع أحدث حوامل وأقسام تجربة الزبائن الفردية بمصانع فزين', 'تركيب واجهات زجاجية كريستالية معالجة ومقاومة لجميع الصدمات'],
    featuresEn: ['Anti-humidity custom oak wall panel integrations', 'Premium localized experience stations from our joinery factory', 'High-impact crystal-clear security glass storefront sheets']
  },
  {
    id: 'laverne_boulevard',
    titleAr: 'لافيرن',
    titleEn: 'Laverne',
    category: 'commercial',
    clientAr: 'لافيرن',
    clientEn: 'Laverne',
    year: '2026',
    area: '450 متر',
    locationAr: 'بوليفار الرياض سيتي',
    locationEn: 'Boulevard Riyadh City',
    descriptionAr: 'تنفيذ كامل ومبهر لمعرض لافيرن الرائد في بوليفارد رياض سيتي، متميزاً بتوافق الهوية البصرية الجريئة وحوائط المايكروسمنت المعتمة والشاشات الرقمية الواسعة والإنارة الراقية.',
    descriptionEn: 'Full-scale contracting and execution for Laverne high-concept fragrance boutique in Blvd Riyadh City, relying on dark micro-cement and digital screens.',
    mainImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000',
    youtubeId: 'ZC2ZWkDyTKQ',
    featuresAr: ['جدران مايكروسمنت داكن مع جص بارز فني فخم', 'تأمين أنظمة إضاءة ثورية غامرة ومسارات نيون مرنة مبهرة', 'دمج شاشات LED عالية الكثافة مع جدران الديكور بسلاسة'],
    featuresEn: ['Dark continuous micro-cement finishes with custom artistic textures', 'Revolutionary flexible neon paths and ambient accent warm paths', 'Concealed surface-mount high-density LED screen layers within the woodwork']
  },
  {
    id: 'assaf_showrooms',
    titleAr: 'عساف',
    titleEn: 'Assaf',
    category: 'commercial',
    clientAr: 'عساف',
    clientEn: 'Assaf',
    year: '2026',
    area: '+500 متر',
    locationAr: '8 مدن مختلفة',
    locationEn: '8 Saudi Cities',
    descriptionAr: 'تنفيذ وتطويع الهوية الكلاسيكية والحديثة لمعارض عطور عساف الممتدة عبر ٨ مدن مختلفة، بروافد جمالية رخامية وتجهيزات عرض خشبية معالجة وذهبية ساحرة.',
    descriptionEn: 'High-end retail branch execution and interior fits for Assaf Perfumes in 8 cities, featuring fine marble counters, custom gold steel brackets, and timber works.',
    mainImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000',
    youtubeId: '6W_QzOo8B_8',
    featuresAr: ['رخام إمبراطوري داكن وذهبي فخم في جميع الأسطح', 'تصنيع أرفف وحوامل بمقاطع مائة الذهب الفينيلية', 'أنظمة تهوية مخفية لسحب وتجديد روائح الهواء الداخلية'],
    featuresEn: ['Dark emperor marble accents with gold metallic details', 'Concealed custom fragrance ventilation paths for continuous air refreshment', 'Gold electroplated custom display shelving lines']
  },
  {
    id: 'wida_hq_office',
    titleAr: 'WIDA',
    titleEn: 'WIDA',
    category: 'office',
    clientAr: 'WIDA',
    clientEn: 'WIDA',
    year: '2026',
    area: '750',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ البيئات المكتبية والمساحات الإدارية المتكاملة لشركة WIDA بمفهوم مستقبلي يجمع بين الأناقة والإنتاجية المطلقة، مع دمج الخشبيات الفاخرة المنتجة في مصانعنا.',
    descriptionEn: 'Turnkey administrative headquarters for WIDA, combining future-proof workspace features with architectural woodwork fabricated in-house.',
    mainImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1000',
    youtubeId: 'sctJkfpe4B4',
    featuresAr: ['تنفيذ قواطع وأبواب زجاجية مبتكرة مزدوجة للعزل الصوتي والخصوصية', 'مساحات مفتوحة وتنسيق إضاءة فعال ومضاد لتعب الأعين ومريح هندسياً', 'مصنعية رفيعة لوحدات الاستقبال الفاخرة المدمجة بالرخام الطبيعي والنحاس'],
    featuresEn: ['Sound-proof double-glazed acoustic partitions and doors', 'Ergonomic low-glare office lighting design paired with collaborative workspaces', 'Bespoke reception island featuring natural raw marble and polished brass sheets']
  },
  {
    id: 'grass_hq_office',
    titleAr: 'جراس',
    titleEn: 'Grass',
    category: 'office',
    clientAr: 'جراس',
    clientEn: 'Grass',
    year: '2026',
    area: '720',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'مكاتب إدارية معاصرة لشركة جراس بالرياض، تجسد مفاهيم الاستدامة والعمارة العضوية بمواد صديقة للبيئة ودهانات خضراء وزخارف عشبية ومعدنية ملهمة.',
    descriptionEn: 'Sustainable active corporate offices executed for Grass Riyadh, displaying bio-architecture details and custom vertical green screens.',
    mainImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000',
    youtubeId: 'RoUGifTAk1c',
    featuresAr: ['تكسية حوائط بخشب السنديان الفاخر الطبيعي والمعالج ضد الحريق والماء', 'دمج تفاصيل بستنة طبيعية بذكاء مع نظم الري الذاتي الصامت', 'أقواص وحواجز معدنية منحنية مطلية بطلاءات كهربائية صديقة للبيئة'],
    featuresEn: ['Fire-resistant natural oak timber wall cladding installations', 'Concealed silent self-watering vertical plant systems', 'Curved steel screens with eco-friendly electrostatic powder paints']
  },
  {
    id: 'mosalla_boutique',
    titleAr: 'مسلى',
    titleEn: 'Mosalla',
    category: 'commercial',
    clientAr: 'مسلى',
    clientEn: 'Mosalla',
    year: '2026',
    area: '350',
    locationAr: 'بريدة',
    locationEn: 'Buraidah',
    descriptionAr: 'تنفيذ ذكي لمتجر ومقر مسلى ببريدة على مساحة متناسقة، برؤية حضرية هادئة تعكس ملمس المايكروسمنت المنسجم والخشبيات المعالجة بنسب فنية عالية الدقة.',
    descriptionEn: 'Exquisite modern showroom build for Mosalla Hub in Buraydah, demonstrating micro-cement facades and natural oak structures.',
    mainImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000',
    youtubeId: '9IUjxFBVpMk',
    featuresAr: ['دهانات وجبس مايكروسمنت بلون سحابي ناعم الملمس وهادئ', 'هندسة وحدات العرض وعربات المحاسبة بمواد عضوية غراء بالكامل', 'أنظمة إضاءة LED غائرة لراحة العين وتجربة فوتوغرافية رائعة'],
    featuresEn: ['Continuous cloudy cloud micro-cement and subtle rendering design', 'Organic non-volatile display counters and POS stations from our workshop', 'Visual performance recessed LED layout for clean, photogenic product shooting']
  },
  {
    id: 'origin_boutique',
    titleAr: 'أورجين',
    titleEn: 'Origin',
    category: 'commercial',
    clientAr: 'أورجين',
    clientEn: 'Origin',
    year: '2026',
    area: '450 متر',
    locationAr: 'الدرعية',
    locationEn: 'Diriyah',
    descriptionAr: 'تنفيذ وتأثيث صالات أورجين الفاخرة في الدرعية، متماشية مع النمط المعماري والبيئة المحيطة، بمزيج غني من الحجر الطبيعي المعتق، وأخشاب السنديان المعتم والإنارة الخافتة.',
    descriptionEn: 'A high-end heritage-aligned fit-out for Origin in Diriyah, combining authentic local stone masonry with heavy darkened oak and warm ambiance.',
    mainImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000',
    youtubeId: 'SVlzQ0HCcpM',
    featuresAr: ['تكسية وتنسيق حوائط حجرية طبيعية معتمدة من تطوير الدرعية', 'أسقف خشبية تقليدية معالجة ضد الرطوبة وعوامل الزمن', 'إضاءات سبوتلايت دافئة غامرة تبرز الزوايا والنحوت الفريدة'],
    featuresEn: ['Local stone cladding approved by Diriyah Gate Development Authority', 'Traditional timber heritage-aligned frames', 'Warm structural narrow spotlights creating luxury contrast on raw stoneworks']
  },
  {
    id: 'optionb_boutique',
    titleAr: 'أوبشن بي',
    titleEn: 'Option B',
    category: 'commercial',
    clientAr: 'أوبشن بي',
    clientEn: 'Option B',
    year: '2026',
    area: '90 متر',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ كامل في وقت قياسي وبأعلى معايير الحرفية لمتجر ومعرض أوبشن بي بالرياض، بمساحة ٩٠ متراً مربعاً مع تجهيز واجهة وخطوط ستيل سوداء مذهلة مع الإضاءات.',
    descriptionEn: 'Rapid record-breaker commercial execution for Option B Store in Riyadh, detailing modern black steel trims, premium finishes, and integrated custom lights.',
    mainImage: 'https://images.unsplash.com/photo-1513885045260-6b15d67e44f9?q=80&w=1000',
    youtubeId: 'zvuyGKVWoF8',
    featuresAr: ['تشطيب فوري متكامل وتجهيزات بلاط معالجة ومقاومة للاهتراء', 'تصنيع إطارات وخطوط ستيل أسود داكن بمسارات إضاءة نيون غامرة', 'لوحة اسم العلامة مضيئة ببريق متوازن مريح للبصر بالواجهة'],
    featuresEn: ['Rapid fit-out execution utilizing wear-resistant high-efficiency tiling', 'Bespoke dark steel contours hosting flush integrated neon runs', 'Aesthetic glowing primary signage with non-glare balanced luminance']
  },
  {
    id: 'lunaspa_store',
    titleAr: 'لونا سبا',
    titleEn: 'Luna Spa',
    category: 'commercial',
    clientAr: 'لونا سبا',
    clientEn: 'Luna Spa',
    year: '2026',
    area: '82',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ راقي وحساس لمعرض وتجهيزات لونا سبا بالرياض بمساحة ٨٢ متراً مربعاً، يخلق تجربة استرخاء وهدوء قصوى بفضل الخشبيات المنحنية والمياه المدمجة والإضاءة الحالمة.',
    descriptionEn: 'Exquisite, luxury-laden execution for Luna Spa showroom in Riyadh on an 82sqm layout, delivering serene ambiance by combining running water elements and curved woodwork.',
    mainImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000',
    youtubeId: '_uNIHH_po0k',
    featuresAr: ['جدران وحوائط خشبية منحنية صامتة بدقة تامة وبدون مسامير مرئية', 'ممرات إنارة مخفية في الأسقف المستعارة للأجواء الحالمة والهادئة', 'أرضيات سيراميك غير منزلقة مخصصة لتوزيع وعزل حراري ممتاز'],
    featuresEn: ['Flawless seamless acoustic curved timber walls with invisible joints', 'Ultra-indirect hidden cove LED layout for supreme visual comfort and calm', 'Premium anti-slip warm-textured ceramic floor tiles for supreme wet-use durability']
  }
];

export const MethodologySteps = [
  {
    step: '01',
    titleAr: 'بداية المشروع',
    titleEn: 'Project Initiation',
    descAr: 'نحو بداية واضحة لمشروع مدروس بعناية.',
    descEn: 'Towards a clear, well-studied start for a meticulously planned project.'
  },
  {
    step: '02',
    titleAr: 'الدراسة والتحليل',
    titleEn: 'Study & Analysis',
    descAr: 'نحلل متطلبات العميل والمخططات والوضع الراهن لبناء رؤية تنفيذية دقيقة وواضحة.',
    descEn: 'We analyze client requirements, schematics, and existing state to build an accurate, clear execution roadmap.'
  },
  {
    step: '03',
    titleAr: 'إعداد جداول الكميات والتسعير',
    titleEn: 'BOQ & Pricing Prep',
    descAr: 'نعد جداول كميات شاملة تغطي جميع بنود المشروع مع تسعير دقيق ومدروس.',
    descEn: 'Preparing comprehensive Bills of Quantities covering all project elements with precise, studied pricing.'
  },
  {
    step: '04',
    titleAr: 'خطة تنفيذ المشروع',
    titleEn: 'Project Execution Plan',
    descAr: 'نضع خطة تنفيذ متكاملة تشمل الجدول الزمني ومراحل المشروع وتسلسل الأعمال.',
    descEn: 'Formulating an integrated execution plan including timelines, milestones, and workflow sequencing.'
  },
  {
    step: '05',
    titleAr: 'التنفيذ',
    titleEn: 'Execution',
    descAr: 'نُنفذ المشروع وفق أعلى معايير الجودة مع متابعة دقيقة لكافة مراحل العمل.',
    descEn: 'Executing the project in accordance with the highest quality standards, closely tracking all phases of work.'
  },
  {
    step: '06',
    titleAr: 'التسليم',
    titleEn: 'Delivery & Handover',
    descAr: 'نُسلم المشروع جاهزاً بعد مراجعة شاملة تضمن اكتمال التفاصيل بأعلى جودة ممكنة.',
    descEn: 'Delivering the project fully completed after a comprehensive audit to guarantee flawless execution.'
  }
];

export const Translations = {
  ar: {
    navHome: 'الرئيسية',
    navProjects: 'مشاريعنا',
    navQuote: 'احصل على عرض سعر',
    companySub: 'فزين للمقاولات المعمارية',
    heroTagline: 'نبني تجربة مميزة',
    heroDesc: 'متخصصون في تنفيذ المحلات التجارية الفاخرة، المكاتب الإدارية الذكية، والبوثات المعمارية في الفعاليات الكبرى. نحول رؤيتك إلى واقع مبهر ومصنع بأعلى درجات الجودة وبأعرق الأخشاب والرخام.',
    btnStart: 'ابدأ مشروعك الآن',
    btnLearnMore: 'استكشف خدماتنا',
    sectionServices: 'خدماتنا الاحترافية',
    sectionServicesSub: 'حلول وحرفية رفيعة ترتقي ببيئة التجزئة والعمل والفعاليات',
    sectionWorks: 'مشاريع منجزة',
    sectionWorksSub: 'معارض التجزئة، المقرات الذكية، والبوثات الإبداعية التي قمنا بإنشائها',
    btnAllProjects: 'تصفح كافة المشاريع',
    sectionMethod: 'منهجية العمل في فزين',
    sectionMethodSub: 'رحلة متكاملة من التخطيط المتقن إلى التصنيع الداخلي والتشطيب الميداني الفاخر',
    sectionQuote: 'طلب دراسة مشروع وعرض سعر',
    sectionQuoteSub: 'املأ تفاصيل مشروعك وسيقوم خبراؤنا بدراسة المساحة وتقديم عرض متكامل ومخطط مبدئي مجاني',
    quoteFormName: 'الاسم بالكامل',
    quoteFormCompany: 'اسم الجهة أو العلامة التجارية',
    quoteFormEmail: 'البريد الإلكتروني',
    quoteFormPhone: 'رقم الجوال (مع الرمز الدولي)',
    quoteFormType: 'نوع الخدمة المطلوبة',
    quoteFormArea: 'مساحة الموقع التقريبية (متر مربع)',
    quoteFormBudget: 'الميزانية التقريبية المقدرة',
    quoteFormTimeline: 'الجدول الزمني المستهدف للتنفيذ',
    quoteFormDetails: 'تفاصيل ومواصفات المشروع الإضافية',
    quoteFormSubmit: 'إرسال طلب دراسة المشروع',
    quoteFormSuccess: 'تم إرسال طلبك بنجاح! سيقوم مستشارونا الهندسيون بالتواصل معك في غضون 24 ساعة',
    retailStore: 'تنفيذ المحلات التجارية',
    officeFit: 'تنفيذ المكاتب والشركات',
    boothFit: 'تنفيذ البوثات والمعارض',
    specsHeader: 'تتضمن الخدمة:',
    budgetUnder50k: 'أقل من 50,000 ريال سعودي',
    budget50k150k: '50,000 إلى 150,000 ريال سعودي',
    budget150k500k: '150,000 إلى 500,000 ريال سعودي',
    budgetOver500k: 'أكثر من 500,000 ريال سعودي',
    timelineUrgent: 'عاجل جداً (أقل من شهر)',
    timelineNormal: 'طبيعي (من شهر إلى 3 أشهر)',
    timelineFlexible: 'مرن (أكثر من 3 أشهر)',
    filterAll: 'الكل',
    filterCommercial: 'محلات تجارية',
    filterOffice: 'مكاتب ومقرات عمل',
    filterBooth: 'بوثات ومعارض',
    projectOverview: 'ملخص مواصفات المشروع',
    projectClient: 'العميل',
    projectLocation: 'الموقع',
    projectYear: 'سنة التنفيذ',
    projectArea: 'المساحة',
    projectFeatures: 'أبرز مميزات التنفيذ',
    footerAbout: 'شركة سعودية متخصصة في أعمال المقاولات وحلول التنفيذ للمشاريع التجارية والمكتبية والبوثات بأحدث التقنيات وفريق عمل خبير واحترافي',
    footerLinks: 'حساباتنا',
    footerContact: 'للتواصل',
    footerRights: 'جميع الحقوق محفوظة. شركة فزين للمقاولات المعمارية ©'
  },
  en: {
    navHome: 'Home',
    navProjects: 'Our Projects',
    navQuote: 'Get a Quote',
    companySub: 'PHZYN Architectural Contracting',
    heroTagline: 'We Build Unique Experiences',
    heroDesc: 'Specialized in premium retail space fit-outs, smart corporate headquarters, and exhibition structures. We turn your vision into physical landmarks made of top-tier timber, customized metallurgy, and marble.',
    btnStart: 'Start Your Journey Now',
    btnLearnMore: 'Explore Our Services',
    sectionServices: 'Our Craftsmanship',
    sectionServicesSub: 'Premium bespoke solutions that elevate retail, workplace, and exhibition spheres',
    sectionWorks: 'Our Portfolio',
    sectionWorksSub: 'Pristine landmarks crafted with state-of-the-art detailing & execution',
    btnAllProjects: 'Browse All Projects',
    sectionMethod: 'Our Rigorous Methodology',
    sectionMethodSub: 'A seamless journey from pristine structural models to in-house wood fabrication',
    sectionQuote: 'Request an Estimate & Study',
    sectionQuoteSub: 'Submit project parameters and receive a structured layout evaluation and preliminary estimate',
    quoteFormName: 'Full Name',
    quoteFormCompany: 'Entity Name or Brand (Optional)',
    quoteFormEmail: 'Email Address',
    quoteFormPhone: 'Mobile Phone (With Country Code)',
    quoteFormType: 'Required Service Type',
    quoteFormArea: 'Approximate Area Size (sqm)',
    quoteFormBudget: 'Project Target Budget',
    quoteFormTimeline: 'Target Execution Schedule',
    quoteFormDetails: 'Additional Scope Requirements & Details',
    quoteFormSubmit: 'Submit Request for Design Study',
    quoteFormSuccess: 'Submitted successfully! Our team will follow up in 24 hours.',
    retailStore: 'Retail Fit-out',
    officeFit: 'Corporate & Office Fit-out',
    boothFit: 'Exhibition Stands & Pavilions',
    specsHeader: 'Service Deliverables:',
    budgetUnder50k: 'Below 50,000 SAR',
    budget50k150k: '50,000 to 150,000 SAR',
    budget150k500k: '150,000 to 500,000 SAR',
    budgetOver500k: 'Above 500,000 SAR',
    timelineUrgent: 'Urgent (Less than 1 month)',
    timelineNormal: 'Standard (1 to 3 months)',
    timelineFlexible: 'Flexible (More than 3 months)',
    filterAll: 'All',
    filterCommercial: 'Retail Stores',
    filterOffice: 'Offices & Firms',
    filterBooth: 'Booths & Pavilions',
    projectOverview: 'Project Specifications',
    projectClient: 'Client',
    projectLocation: 'Location',
    projectYear: 'Year',
    projectArea: 'Area Size',
    projectFeatures: 'Key Fit-out Features',
    footerAbout: 'A Saudi company specialized in contracting works and implementation solutions for commercial, office, and booth projects with the latest technologies and an expert, professional team.',
    footerLinks: 'Our Accounts',
    footerContact: 'Contact Us',
    footerRights: 'All rights reserved. PHZYN Architectural Contracting ©'
  }
};
