/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Service, Project } from './types';
import imgCommercial from './assets/images/regenerated_image_1779550936996.png';
import imgOffice from './assets/images/regenerated_image_1779550938782.png';
import imgBooth from './assets/images/regenerated_image_1779550940143.png';

export const ServicesData: Service[] = [
  {
    id: 'commercial',
    titleAr: 'تنفيذ المحلات التجارية',
    titleEn: 'Retail Store Fit-out',
    descriptionAr: 'نصنع لعلامتك التجارية حضوراً حسّياً مبهراً يلفت الأنظار، عبر تنفيذ وتشطيب معارض التجزئة ومحلات العطور والملابس الفاخرة بأعلى معايير الإتقان والدقة الهندسية.',
    descriptionEn: 'We craft an elegant physical presence for your brand, constructing and finishing luxury showrooms, fragrance boutiques, and high-end fashion stores with architectural precision.',
    icon: 'Store',
    image: imgCommercial,
    specsAr: ['تشطيب كامل للأقسام الكبرى', 'تصنيع وتوريد وحدات العرض الخشبية والمعدنية المخصصة', 'أنظمة الإضاءة الدراماتيكية لإبراز المنتجات', 'دمج الهويات البصرية للعلامات العالمية والمحلية'],
    specsEn: ['Turnkey luxury retail checkout and shopping halls', 'Custom woodwork and metal display units manufacturing', 'Dramatic aesthetic lighting plans for product highlights', 'Seamless brand identity integration for global & local brands']
  },
  {
    id: 'office',
    titleAr: 'تنفيذ المكاتب والشركات',
    titleEn: 'Office & Corporate Fit-out',
    descriptionAr: 'نصمم وننفذ بيئات عمل تفاعلية تجمع بين جودة التشطيب والعملية المطلقة، مع مراعاة العزل الصوتي وتوزيع الهياكل، لخلق مساحات تحفز الإنتاجية وتعكس هيبة شركتك.',
    descriptionEn: 'We execute interactive workplaces combining premier finishes with ultimate ergonomics. Featuring sound insulation, acoustic partitions, and structures that boost performance and command prestige.',
    icon: 'Briefcase',
    image: imgOffice,
    specsAr: ['تركيب القواطع الزجاجية والصوتية المبتكرة', 'تنفيذ غرف الاجتماعات الذكية والـ CEO Suites الفاخرة', 'توزيع الإضاءة المريحة للعين وخافضة للجهد', 'تجهيز البنية التحتية المتكاملة للشبكات والتيار الخفيف'],
    specsEn: ['Acoustic double-glazed smart partitions', 'Luxury CEO Suites and premium multimedia boardrooms', 'Anti-glare work-comfort lighting distribution', 'Complete low-voltage utility and networking infrastructure']
  },
  {
    id: 'booth',
    titleAr: 'تنفيذ البوثات والمعارض',
    titleEn: 'Exhibition Booths & Pavilions',
    descriptionAr: 'نحول البوثات المؤقتة إلى معالم معمارية جذابة في المعارض الدولية والفعاليات الكبرى، بإنشاء هياكل هندسية مخصصة وسريعة التجميع تنبض بروح علامتك التجارية.',
    descriptionEn: 'We transform temporary structures into architectural landmarks at international exhibitions and major events, building custom, quick-assembly structures that pulse with your brand identity.',
    icon: 'Layers',
    image: imgBooth,
    specsAr: ['تصنيع الهياكل الخشبية المنحنية والمقساة مسبقاً', 'تركيب شاشات العرض الذكية وحلول التفاعل الرقمي', 'توفير أنظمة إضاءة نيون وميتاليك جذابة', 'سرعة التنفيذ والتفكيك مع الحفاظ على سلامة المواد'],
    specsEn: ['Pre-fabricated custom curved and high-strength timber arches', 'Interactive digital signage and LED walls integration', 'Metallic and vivid neon visual lighting systems', 'High-speed assembly and teardown operations with material retention']
  }
];

export const ProjectsData: Project[] = [
  {
    id: 'kitami',
    titleAr: 'مطعم كيتامي - بريدة',
    titleEn: 'Kitami Restaurant - Buraydah',
    category: 'commercial',
    clientAr: 'مطعم كيتامي',
    clientEn: 'Kitami',
    year: '2025',
    area: '180 م²',
    locationAr: 'القصيم، بريدة',
    locationEn: 'Qassim, Buraydah',
    descriptionAr: 'تنفيذ كامل وتشطيب لمطعم كيتامي ببريدة بأعلى مستويات الإبداع الهندسي والجمالي العصري، تبرز بالخشبيات الفخمة والإضاءة المريحة والمنسقة.',
    descriptionEn: 'Full high-end fit-out and execution for Kitami Restaurant in Buraydah, achieving exquisite modern dining atmospheres and bespoke wooden elements.',
    mainImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1000',
    youtubeId: 'jvIuAI9vFWA',
    featuresAr: ['أنظمة إنارة خافتة ومريحة مصممة هندسياً', 'وحدات الجدران الخشبية المنفذة بدقة بالغة', 'طاولات وأعمال معدنية مخصصة بمصانع فزين', 'تشطيبات وتكسية أرضيات وحوائط بمظهر معاصر فخم'],
    featuresEn: ['Sleek, warm and premium dining lighting layouts', 'Bespoke high-end wood panel accents and fixtures', 'Custom metallurgy and fine furniture executed in-house', 'Polished top-tier floor and wall finish treatments']
  },
  {
    id: 'wida',
    titleAr: 'مكتب شركة WIDA - الرياض',
    titleEn: 'WIDA Corporate Office - Riyadh',
    category: 'office',
    clientAr: 'شركة WIDA',
    clientEn: 'WIDA Company',
    year: '2025',
    area: '700 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ البيئات المكتبية والمساحات الإدارية المتكاملة لشركة WIDA بمفهوم مستقبلي يجمع بين الأناقة والإنتاجية المطلقة، مع دمج الخشبيات الفاخرة المنتجة في مصانعنا.',
    descriptionEn: 'Innovative workspace layout and full premium execution for WIDA Corporate Office in Riyadh, combining modern aesthetic warmth with high-performance employee zones.',
    mainImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1000',
    youtubeId: 'oBjuI3Pj18c',
    featuresAr: ['عوازل صوتية مبتكرة للجدران والأسقف', 'قواطع زجاجية مزدوجة معالجة للخصوصية', 'تصميم إضاءة ديناميكي يعزز التركيز والراحة', 'مكتب استقبال فخم بلمسات نحاسية بالغة الرقي'],
    featuresEn: ['Premium sound-proofing on executive walls & ceiling grids', 'Double-glazed sleek architectural partition screens', 'Dynamic anti-glare active office lighting setups', 'Elegant reception lobby with signature custom-welded brass']
  },
  {
    id: 'floward',
    titleAr: 'مكتب شركة فلاورد - الرياض',
    titleEn: 'Floward Office - Riyadh',
    category: 'office',
    clientAr: 'شركة فلاورد',
    clientEn: 'Floward',
    year: '2025',
    area: '1500 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'بيئة عمل حديثة ومساحات مكتبية متكاملة لشركة فلاورد، تشمل مكاتب مفتوحة مفعمة بالحيوية ومناطق ترفيهية ذكية واجتماعات تفاعلية مبهرة.',
    descriptionEn: 'Dynamic corporate workspace design and realization for Floward\'s head office in Riyadh, emphasizing open-collaboration lounges and smart structural elements.',
    mainImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000',
    youtubeId: 'lUm6rthYZPU',
    featuresAr: ['قاعات اجتماعات ذكية بنظام صوتي ومرئي متطور', 'مساحات عمل مفتوحة تعزز بيئة التعاون والإبداع', 'تفاصيل ونباتات داخلية تضفي لمسة حيوية', 'أنظمة تحكم ذكية بالإضاءة والتكييف'],
    featuresEn: ['Integrated high-end media systems & smart boardrooms', 'Open-space collaborative desk grids and lounges', 'Biophilic organic indoor scenery integration', 'Automated centralized lighting & climate modules']
  },
  {
    id: 'grass',
    titleAr: 'مكتب شركة جراس - الرياض',
    titleEn: 'Grass Office - Riyadh',
    category: 'office',
    clientAr: 'شركة جراس',
    clientEn: 'Grass',
    year: '2025',
    area: '400 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'مكاتب إدارية معاصرة لشركة جراس بالرياض تم تصميمها وتنفيذها لتعكس الاستدامة والنمو، تبرز بالخامات الخشبية ولمسات خضراء ناضرة.',
    descriptionEn: 'A state-of-the-art office fit-out for Grass office in Riyadh, bringing together seamless wooden detailing and fresh sustainable design materials.',
    mainImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000',
    youtubeId: 'Zw54FjqVNEs',
    featuresAr: ['تكسية جدران بأخشاب طبيعية ممتازة ومعالجة', 'توزيع إضاءة ناعمة وخافضة للجهد تعزز التركيز والإنتاجية', 'مناطق انتظار فخمة ومريحة للزوار والعملاء', 'أعمال حدادة مخصصة للفواصل وقواطع الغرف'],
    featuresEn: ['Handcrafted natural oak wood wall panels', 'Low-glare task comfort lighting installations', 'Spacious executive lobby and lounge setups', 'Custom architectural steel and glass partitioning']
  },
  {
    id: 'sccp',
    titleAr: 'مكتب SCCP - الرياض',
    titleEn: 'SCCP Office - Riyadh',
    category: 'office',
    clientAr: 'مكتب SCCP',
    clientEn: 'SCCP Office',
    year: '2025',
    area: '100 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'مكتب خاص مدمج ومصمم برؤية معمارية فريدة تستغل المساحة بكفاءة تامة، ممزوجاً بتشطيب راقي وغني بالرخام والخشب والمعدن.',
    descriptionEn: 'An ultra-exclusive compact private executive office for SCCP in Riyadh, proving that absolute luxury is in the fine details and premium hardware.',
    mainImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1000',
    youtubeId: 'FuEhmSeYuYU',
    featuresAr: ['تكسيات جدارية خشبية ورخامية متناغمة', 'طاولات ومقاعد إدارية فاخرة ومخصصة', 'إضاءات LED خطية ومخفية لزيادة العمق البصري', 'عزل صوتي فائق للجدران وقسيمة الباب الرئيسي'],
    featuresEn: ['Integrated polished marble slabs with fluted timber', 'Bespoke executive leather chairs and active task desks', 'Dimmable linear LED wall guides for spacious depth', 'Acoustically soundproofed drywall structure & heavy doors']
  },
  {
    id: 'knaf',
    titleAr: 'معرض كناف - الرياض',
    titleEn: 'Knaf Boutique - Riyadh',
    category: 'commercial',
    clientAr: 'كناف',
    clientEn: 'Knaf',
    year: '2025',
    area: '100 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'تنفيذ معرض كناف في الرياض بهوية بصرية ساحرة وإتقان هندسي رائع بالمايكروسمنت المخفف وتصاميم منحنيات هادئة.',
    descriptionEn: 'Stunning execution for Knaf retail boutique in Riyadh, featuring soft curves, custom-textured plaster finishes, and premium display accents.',
    mainImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1000',
    youtubeId: 'fVDT0XMdHqA',
    featuresAr: ['تشطيب جدران بجص دقيق الملمس ومنحوت', 'أرفف عرض مدمجة بإضاءات ناعمة متجانسة', 'بلاط وأرضيات حجرية طبيعية معالجة', 'هياكل عرض مصممة خصيصاً بمصانع فزين'],
    featuresEn: ['Artisanal meticulously sculpted plaster wall overlays', 'Recessed showcase shelves with smooth warm backlight halos', 'Finely treated heavy-duty natural stone tiling', 'Custom-tailored center showcases manufactured in-house']
  },
  {
    id: 'rasmah',
    titleAr: 'معارض رسمة - عدة مواقع',
    titleEn: 'Rasmah Boutique - Multiple Sites',
    category: 'commercial',
    clientAr: 'رسمة',
    clientEn: 'Rasmah',
    year: '2025',
    area: 'أكثر من 500 م²',
    locationAr: 'عدة مواقع في المملكة',
    locationEn: 'Multiple Locations, KSA',
    descriptionAr: 'تنفيذ وتجهيز سلسلة معارض رسمة في عدة مدن بالمملكة، بتشطيب فاخر وتصميم هندسي يستعرض المنتجات بأناقة مطلقة واهتمام دقيق بالتفاصيل.',
    descriptionEn: 'Turnkey commercial multi-store rollout for Rasmah Beauty boutiques across several cities in Saudi Arabia, with absolute consistency and prime luxury finishes.',
    mainImage: 'https://images.unsplash.com/photo-1620052581237-5d36667be337?q=80&w=1000',
    youtubeId: '8zUdio5zM4s',
    featuresAr: ['حوائط تشطيب بمظهر المايكروسمنت العصري الهادئ', 'لوحات جدارية مضيئة ومثيرة للانتباه', 'أرفف زجاجية وحوامل معدنية مطلية بمقاومة عالية', 'عربات عرض وتزيين مدمجة بمصانعنا الخشبية والحديدية'],
    featuresEn: ['Polished micro-cement wall facets in a calming gray hue', 'Vividly illuminated statement canvas frames', 'Heavy-duty steel hanger bars and custom glass panels', 'Integrated display counters from our joinery and metal plant']
  },
  {
    id: 'labkah',
    titleAr: 'معرض لبكة - الرياض',
    titleEn: 'Labkah Store - Riyadh',
    category: 'commercial',
    clientAr: 'لبكة',
    clientEn: 'Labkah',
    year: '2025',
    area: '100 م²',
    locationAr: 'الرياض',
    locationEn: 'Riyadh',
    descriptionAr: 'متجر لبكة المتميز بالرياض بمساحة مدروسة تجمع بين الفن البصري المعاصر وجودة التشطيب في الخشبيات ونظم العرض المبتكرة.',
    descriptionEn: 'Bespoke commercial fit-out for Labkah Store in Riyadh, emphasizing elegant custom-molded woodwork and eye-catching product stands.',
    mainImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000',
    youtubeId: 'rXHlcFUOt1I',
    featuresAr: ['خزائن وجدران خشبية منحنية مصممة خصيصاً', 'أضواء تبرز فخامة المعروضات بدقة تامة', 'أرضيات إيبوكسي عالية المقاومة بمظهر رخامي فريد', 'لوحة اسم مضيئة وواجهة زجاجية ممتدة رائعة'],
    featuresEn: ['Custom curved multi-layer timber panel and closet builds', 'Precision accent spotlights prioritizing focal merch', 'Smooth glass-finish epoxy floor with marble-like veins', 'Expansive clear-glass showcase windows and giant lit brand name']
  },
  {
    id: 'aromatic_boutique',
    titleAr: 'معارض أروماتك - مواقع متعددة',
    titleEn: 'Aromatic Boutique Showrooms - Multiple Sites',
    category: 'commercial',
    clientAr: 'أروماتك',
    clientEn: 'Aromatic',
    year: '2025',
    area: 'أكثر من 500 م²',
    locationAr: 'عدة مواقع في المملكة',
    locationEn: 'Multiple Locations, KSA',
    descriptionAr: 'تنفيذ وتأثيث صالات فروع معارض عطور أروماتك الفاخرة، مع حوائط مايكروسمنت معالجة ومرايا جذابة مبرزة بإنارات خاشعة تعكس روح العلامة الفخمة.',
    descriptionEn: 'Turnkey execution and multi-branch rollouts for Aromatic luxury perfume boutique networks, relying on micro-cement finishes and geometric brass counters.',
    mainImage: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=1000',
    youtubeId: 'xfjXgVmL3Kw',
    featuresAr: ['واجهات ومرايا دائرية مضيئة بمقاومة فائقة للرطوبة', 'حوائط ميكروسمنت بلون سحابي مميز', 'طاولات عرض رخامية مخصصة بآلات CNC بمصانعنا', 'أنظمة تهوية مصممة لتوزيع مستمر للرائحة العطرية'],
    featuresEn: ['Sleek circular custom mirrors with vanity-halo lights', 'Textured premium micro-cement coating on raw partitions', 'Preconditioned stone display bars modeled with high-end CNC', 'Aroma diffusion routing directly merged inside false ceiling grids']
  },
  {
    id: 'rasees_store',
    titleAr: 'معارض رسيس - مواقع متعددة',
    titleEn: 'Rasees Showrooms - Multiple Sites',
    category: 'commercial',
    clientAr: 'رسيس',
    clientEn: 'Rasees Perfumes',
    year: '2025',
    area: 'أكثر من 500 م²',
    locationAr: 'عدة مواقع في المملكة',
    locationEn: 'Multiple Locations, KSA',
    descriptionAr: 'تنفيذ وتطبق الهوية البصرية الراقية لمعارض رسيس للعطور بجميع أنحاء المملكة، بتفاصيل ديكورية غنية بالذهبي الفخم والرخام الداكن الاستثنائي.',
    descriptionEn: 'Turnkey high-end retail execution for Rasees Perfumes showrooms across the kingdom, emphasizing gold metal framing and dark imperial marble.',
    mainImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000',
    youtubeId: '_LRMwXNWUSw',
    featuresAr: ['إطارات وقواطع مطلية بماء الذهب والستانلس ستيل المقاوم', 'تصنيع طاولات عرض خشبية سوداء مصقولة بإتقان بمصانع فزين', 'إضاءات سبوتلايت مريحة وخافضة للجهد تبرز الزجاج العطري', 'أقسام تجربة استثنائية للزائرين مرصعة بأرقى الجلود'],
    featuresEn: ['Anodized anti-scratch gold electroplated steel accents', 'Lustrous black-lacquered showcase tables built by fzyn', 'Low-voltage high-index spots focusing on perfume bottles', 'Distinct tester stations beautifully lined with premium leather']
  },
  {
    id: 'alshaya',
    titleAr: 'معارض الشايع - عدة مواقع',
    titleEn: 'AlShaya Showrooms - Multiple Sites',
    category: 'commercial',
    clientAr: 'الشايع',
    clientEn: 'AlShaya',
    year: '2025',
    area: 'أكثر من 350 م²',
    locationAr: 'عدة مواقع في المملكة',
    locationEn: 'Multiple Locations, KSA',
    descriptionAr: 'تنفيذ سلسلة فروع معارض الشايع الفخمة، بلمسات فريدة من الأخشاب الفاخرة والزجاج الملون والإضاءات الغامرة لتجربة تسوق استثنائية.',
    descriptionEn: 'High-standard commercial fit-out and architectural works for AlShaya luxury boutique showrooms, with dynamic lighting integrations and custom millwork.',
    mainImage: 'https://images.unsplash.com/photo-1513885045260-6b15d67e44f9?q=80&w=1000',
    youtubeId: 'KOzjaFhWCRc',
    featuresAr: ['تشطيبات خشبية دافئة وتصاميم حديثة ومريحة', 'طاولات دائرية تفاعلية لعرض الروائح والمنتجات', 'واجهة زجاجية حديثة تمنح إطلالة متسعة', 'أنظمة تحكم وحماية ومراقبة متطورة مدمجة بالسقف'],
    featuresEn: ['Spacious oak finish layout with sleek geometric panels', 'Interactive custom curved display blocks for scent testing', 'Double-glazed high-transparency glass facade structure', 'Integrated subtle smart-security and AV components in ceiling']
  }
];

export const MethodologySteps = [
  {
    step: '01',
    titleAr: 'بداية المشروع',
    titleEn: 'Project Initiation',
    descAr: 'نحو بداية واضحة لمشروع مدروس بعناية.',
    descEn: 'Towards a clear, well-studied start for a meticulously planned project.'
  },
  {
    step: '02',
    titleAr: 'الدراسة والتحليل',
    titleEn: 'Study & Analysis',
    descAr: 'نحلل متطلبات العميل والمخططات والوضع الراهن لبناء رؤية تنفيذية دقيقة وواضحة.',
    descEn: 'We analyze client requirements, schematics, and existing state to build an accurate, clear execution roadmap.'
  },
  {
    step: '03',
    titleAr: 'إعداد جداول الكميات والتسعير',
    titleEn: 'BOQ & Pricing Prep',
    descAr: 'نعد جداول كميات شاملة تغطي جميع بنود المشروع مع تسعير دقيق ومدروس.',
    descEn: 'Preparing comprehensive Bills of Quantities covering all project elements with precise, studied pricing.'
  },
  {
    step: '04',
    titleAr: 'خطة تنفيذ المشروع',
    titleEn: 'Project Execution Plan',
    descAr: 'نضع خطة تنفيذ متكاملة تشمل الجدول الزمني ومراحل المشروع وتسلسل الأعمال.',
    descEn: 'Formulating an integrated execution plan including timelines, milestones, and workflow sequencing.'
  },
  {
    step: '05',
    titleAr: 'التنفيذ',
    titleEn: 'Execution',
    descAr: 'نُنفذ المشروع وفق أعلى معايير الجودة مع متابعة دقيقة لكافة مراحل العمل.',
    descEn: 'Executing the project in accordance with the highest quality standards, closely tracking all phases of work.'
  },
  {
    step: '06',
    titleAr: 'التسليم',
    titleEn: 'Delivery & Handover',
    descAr: 'نُسلم المشروع جاهزاً بعد مراجعة شاملة تضمن اكتمال التفاصيل بأعلى جودة ممكنة.',
    descEn: 'Delivering the project fully completed after a comprehensive audit to guarantee flawless execution.'
  }
];

export const Translations = {
  ar: {
    navHome: 'الرئيسية',
    navProjects: 'مشاريعنا',
    navQuote: 'احصل على عرض سعر',
    companySub: 'فزين للمقاولات المعمارية',
    heroTagline: 'نبني تجربة مميزة',
    heroDesc: 'متخصصون في تنفيذ المحلات التجارية الفاخرة، المكاتب الإدارية الذكية، والبوثات المعمارية في الفعاليات الكبرى. نحول رؤيتك إلى واقع مبهر ومصنع بأعلى درجات الجودة وبأعرق الأخشاب والرخام.',
    btnStart: 'ابدأ مشروعك الآن',
    btnLearnMore: 'استكشف خدماتنا',
    sectionServices: 'خدماتنا الاحترافية',
    sectionServicesSub: 'حلول وحرفية رفيعة ترتقي ببيئة التجزئة والعمل والفعاليات',
    sectionWorks: 'أعمالنا المنجزة',
    sectionWorksSub: 'نفخر ببناء معالم وصروح تجارية وإدارية تشهد بدقتنا',
    btnAllProjects: 'تصفح كافة المشاريع',
    sectionMethod: 'منهجية العمل في فزين',
    sectionMethodSub: 'رحلة متكاملة من التخطيط المتقن إلى التصنيع الداخلي والتشطيب الميداني الفاخر',
    sectionQuote: 'طلب دراسة مشروع وعرض سعر',
    sectionQuoteSub: 'املأ تفاصيل مشروعك وسيقوم خبراؤنا بدراسة المساحة وتقديم عرض متكامل ومخطط مبدئي مجاني',
    quoteFormName: 'الاسم بالكامل',
    quoteFormCompany: 'اسم الجهة أو العلامة التجارية',
    quoteFormEmail: 'البريد الإلكتروني',
    quoteFormPhone: 'رقم الجوال (مع الرمز الدولي)',
    quoteFormType: 'نوع الخدمة المطلوبة',
    quoteFormArea: 'مساحة الموقع التقريبية (متر مربع)',
    quoteFormBudget: 'الميزانية التقريبية المقدرة',
    quoteFormTimeline: 'الجدول الزمني المستهدف للتنفيذ',
    quoteFormDetails: 'تفاصيل ومواصفات المشروع الإضافية',
    quoteFormSubmit: 'إرسال طلب دراسة المشروع',
    quoteFormSuccess: 'تم إرسال طلبك بنجاح! سيقوم مستشارونا الهندسيون بالتواصل معك في غضون 24 ساعة لتقديم المخطط المبدئي وعرض السعر.',
    retailStore: 'تنفيذ المحلات التجارية',
    officeFit: 'تنفيذ المكاتب والشركات',
    boothFit: 'تنفيذ البوثات والمعارض',
    specsHeader: 'تتضمن الخدمة:',
    budgetUnder50k: 'أقل من 50,000 ريال سعودي',
    budget50k150k: '50,000 إلى 150,000 ريال سعودي',
    budget150k500k: '150,000 إلى 500,000 ريال سعودي',
    budgetOver500k: 'أكثر من 500,000 ريال سعودي',
    timelineUrgent: 'عاجل جداً (أقل من شهر)',
    timelineNormal: 'طبيعي (من شهر إلى 3 أشهر)',
    timelineFlexible: 'مرن (أكثر من 3 أشهر)',
    filterAll: 'الكل',
    filterCommercial: 'المحلات التجارية',
    filterOffice: 'المكاتب والمؤسسات',
    filterBooth: 'البوثات والأجنحة',
    projectOverview: 'ملخص مواصفات المشروع',
    projectClient: 'العميل',
    projectLocation: 'الموقع',
    projectYear: 'سنة التنفيذ',
    projectArea: 'المساحة',
    projectFeatures: 'أبرز مميزات التنفيذ',
    footerAbout: 'شركة سعودية متخصصة في أعمال المقاولات وحلول التنفيذ للمشاريع التجارية والمكتبية والبوثات بأحدث التقنيات وفريق عمل خبير واحترافي',
    footerLinks: 'حساباتنا',
    footerContact: 'للتواصل',
    footerRights: 'جميع الحقوق محفوظة. شركة فزين للمقاولات المعمارية ©'
  },
  en: {
    navHome: 'Home',
    navProjects: 'Our Projects',
    navQuote: 'Get a Quote',
    companySub: 'PHZYN Architectural Contracting',
    heroTagline: 'We Build Unique Experiences',
    heroDesc: 'Specialized in premium retail space fit-outs, smart corporate headquarters, and exhibition structures. We turn your vision into physical landmarks made of top-tier timber, customized metallurgy, and marble.',
    btnStart: 'Start Your Journey Now',
    btnLearnMore: 'Explore Our Services',
    sectionServices: 'Our Craftsmanship',
    sectionServicesSub: 'Premium bespoke solutions that elevate retail, workplace, and exhibition spheres',
    sectionWorks: 'Our Portfolio',
    sectionWorksSub: 'Pristine landmarks crafted with state-of-the-art detailing & execution',
    btnAllProjects: 'Browse All Projects',
    sectionMethod: 'Our Rigorous Methodology',
    sectionMethodSub: 'A seamless journey from pristine structural models to in-house wood fabrication',
    sectionQuote: 'Request an Estimate & Study',
    sectionQuoteSub: 'Submit project parameters and receive a structured layout evaluation and preliminary estimate',
    quoteFormName: 'Full Name',
    quoteFormCompany: 'Entity Name or Brand (Optional)',
    quoteFormEmail: 'Email Address',
    quoteFormPhone: 'Mobile Phone (With Country Code)',
    quoteFormType: 'Required Service Type',
    quoteFormArea: 'Approximate Area Size (sqm)',
    quoteFormBudget: 'Project Target Budget',
    quoteFormTimeline: 'Target Execution Schedule',
    quoteFormDetails: 'Additional Scope Requirements & Details',
    quoteFormSubmit: 'Submit Request for Design Study',
    quoteFormSuccess: 'Submitted successfully! Our lead architect will follow up in 24 hours with a free initial floor block layout and budget estimate.',
    retailStore: 'Retail Fit-out',
    officeFit: 'Corporate & Office Fit-out',
    boothFit: 'Exhibition Stands & Pavilions',
    specsHeader: 'Service Deliverables:',
    budgetUnder50k: 'Below 50,000 SAR',
    budget50k150k: '50,000 to 150,000 SAR',
    budget150k500k: '150,000 to 500,000 SAR',
    budgetOver500k: 'Above 500,000 SAR',
    timelineUrgent: 'Urgent (Less than 1 month)',
    timelineNormal: 'Standard (1 to 3 months)',
    timelineFlexible: 'Flexible (More than 3 months)',
    filterAll: 'All',
    filterCommercial: 'Retail Stores',
    filterOffice: 'Offices & Firms',
    filterBooth: 'Booths & Pavilions',
    projectOverview: 'Project Specifications',
    projectClient: 'Client',
    projectLocation: 'Location',
    projectYear: 'Year',
    projectArea: 'Area Size',
    projectFeatures: 'Key Fit-out Features',
    footerAbout: 'A Saudi company specialized in contracting works and implementation solutions for commercial, office, and booth projects with the latest technologies and an expert, professional team.',
    footerLinks: 'Our Accounts',
    footerContact: 'Contact Us',
    footerRights: 'All rights reserved. PHZYN Architectural Contracting ©'
  }
};
